create table "public"."components" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "component_name" text,
    "component_options" text,
    "component_int_variable" smallint
);


alter table "public"."components" enable row level security;

alter table "public"."sites" add column "banner_url" text;

alter table "public"."sites" add column "name" text;

alter table "public"."sites" add column "pfp_url" text;

alter table "public"."sites" add column "twitter_bio" text;

CREATE UNIQUE INDEX components_pkey ON public.components USING btree (id);

alter table "public"."components" add constraint "components_pkey" PRIMARY KEY using index "components_pkey";

grant delete on table "public"."components" to "anon";

grant insert on table "public"."components" to "anon";

grant references on table "public"."components" to "anon";

grant select on table "public"."components" to "anon";

grant trigger on table "public"."components" to "anon";

grant truncate on table "public"."components" to "anon";

grant update on table "public"."components" to "anon";

grant delete on table "public"."components" to "authenticated";

grant insert on table "public"."components" to "authenticated";

grant references on table "public"."components" to "authenticated";

grant select on table "public"."components" to "authenticated";

grant trigger on table "public"."components" to "authenticated";

grant truncate on table "public"."components" to "authenticated";

grant update on table "public"."components" to "authenticated";

grant delete on table "public"."components" to "service_role";

grant insert on table "public"."components" to "service_role";

grant references on table "public"."components" to "service_role";

grant select on table "public"."components" to "service_role";

grant trigger on table "public"."components" to "service_role";

grant truncate on table "public"."components" to "service_role";

grant update on table "public"."components" to "service_role";


